### ISSUE TITLE
more complete dark mode

### ISSUE THREAD

**Issue by mark-pictor-csec** [golang-design/ssaplayground#14]
I'm glad to see a dark mode for the output view, but the rest of the UI remains pretty bright.

With Chrome's Stylus extension, the following is enough to dim the remainder. Feel free to pick better colors, of course! 🙂 
```css
#banner{
    background-color:#566;
}
#snippet,#about{
    background-color:#665;
}
#funcname, #gcflags {
    background-color: #343;
    border: 1px solid #454;
}
.gutter.gutter-horizontal {
    filter: invert(.7);
}
input[type=button] {
    background: #0044cb;
    color: #000;
}
```
